### ISSUE TITLE
Initial set up

### ISSUE THREAD

**Issue by lestece** [lestece/bibliofile-api#2]
Create the Django project and set it up to use Cloudinary.

## Tasks:
- [x] Install Django
- [x] Install Cloudinary storage
- [x] Install DRF
- [x] Create env.py file
- [x] Adjust the settings accordingly
